const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='glad_test_v2';
const exercises=[
{id:'1A',name:'Bekken liften',page:5,img:'assets/page-05.png',levels:4},
{id:'1B',name:'Sit-ups',page:6,img:'assets/page-06.png',levels:4},
{id:'2A',name:'Achterwaarts glijden & lunges',page:7,img:'assets/page-07.png',levels:4},
{id:'2B',name:'Zijwaarts glijden & lunges',page:8,img:'assets/page-08.png',levels:4},
{id:'3A',name:'Heup abductoren',page:9,img:'assets/page-09.png',levels:4},
{id:'3B',name:'Heup adductoren',page:10,img:'assets/page-10.png',levels:4},
{id:'3C',name:'Knie buigers',page:11,img:'assets/page-11.png',levels:4},
{id:'3D',name:'Knie strekkers',page:12,img:'assets/page-12.png',levels:4},
{id:'4A',name:'Opstaan uit de stoel',page:13,img:'assets/page-13.png',levels:4},
{id:'4B',name:'Steps',page:14,img:'assets/page-14.png',levels:4}
];
let state=loadState(),unlocked=false,dirty=false;
function defaultState(){return {profile:null,pinHash:null,zones:{greenMax:2,orangeMax:5},sessions:{},lastSaved:null}}
function loadState(){try{let v=JSON.parse(localStorage.getItem(KEY)||'{}');if(!v.profile){let old=JSON.parse(localStorage.getItem('glad_test_v1')||'{}');if(old.profile)v={...old,zones:{greenMax:2,orangeMax:5}}}return {...defaultState(),...v}}catch{return defaultState()}}
function persist(){state.lastSaved=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));dirty=false;updateSaveStatus('Opgeslagen '+new Date().toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'}))}
async function hash(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function validPin(v){return /^\d{4,8}$/.test(v)} function todayISO(){return new Date().toISOString().slice(0,10)}
function currentSession(){const d=$('#sessionDate').value||todayISO();return state.sessions[d]??=( {date:d,painBefore:'',painAfter:'',painLater:'',painNextDay:'',pain24h:false,note:'',warmup:{minutes:10,effort:''},exercises:{}})}
function zoneFor(n){n=Number(n);if(n<=2)return ['safe','🙂','Veilig'];if(n<=5)return ['accept','😐','Acceptabel'];return ['avoid','☹️','Vermijd']}
function painOptions(){return '<option value="">–</option>'+Array.from({length:11},(_,i)=>`<option value="${i}">${i} ${zoneFor(i)[1]} ${zoneFor(i)[2]}</option>`).join('')}
function renderLegend(){$('#painLegend').innerHTML='<div class="zone safe"><span class="face">🙂</span>Veilig<br><small>0–2</small></div><div class="zone accept"><span class="face">😐</span>Acceptabel<br><small>&gt;2–5</small></div><div class="zone avoid"><span class="face">☹️</span>Vermijd<br><small>&gt;5–10</small></div><p class="legend-note">Volgens het GLA:D-handboek: bij pijn boven 5 is vaak aanpassing in overleg met de fysiotherapeut nodig. Ook verhoogde pijn die langer dan 24 uur aanhoudt is een signaal om het programma te bespreken.</p>'}
function renderExercises(){const s=currentSession();$('#exerciseList').innerHTML=exercises.map(ex=>{const v=s.exercises[ex.id]||{level:'',pain:'',sets:'',reps:''};return `<div class="card exercise-card" data-ex="${ex.id}"><div class="exercise-head"><button class="photo-button" data-img="${ex.img}" data-title="${ex.id} ${ex.name}"><img class="exercise-photo-img" src="${ex.img}" alt="GLA:D ${ex.id} ${ex.name}, pagina ${ex.page}"></button><div class="exercise-title"><div class="eyebrow">Oefening ${ex.id} · p. ${ex.page}</div><h3>${ex.name}</h3><span class="pain-pill ${v.pain!==''?zoneFor(v.pain)[0]+'P':''}">${v.pain!==''?zoneFor(v.pain)[1]+' pijn '+v.pain:'Nog niet geregistreerd'}</span></div></div><div class="exercise-controls"><label>Niveau<select class="ex-level"><option value="">–</option>${[1,2,3,4].map(i=>`<option ${String(i)===String(v.level)?'selected':''}>${i}</option>`).join('')}</select></label><label>Sets<input class="ex-sets" type="number" min="0" max="5" value="${v.sets||''}" placeholder="2–3"></label><label>Herhalingen / set<input class="ex-reps" type="number" min="0" max="50" value="${v.reps||''}" placeholder="10–15"></label><label>Pijn 0–10<select class="ex-pain">${painOptions()}</select></label></div><button class="secondary save-one">Oefening opslaan</button></div>`}).join('');
$$('.exercise-card').forEach(card=>{const id=card.dataset.ex,val=s.exercises[id];if(val?.pain!==undefined)card.querySelector('.ex-pain').value=val.pain;card.querySelector('.save-one').onclick=()=>{s.exercises[id]=readExercise(card);dirty=true;persist();renderExercises();renderAlert()};card.querySelectorAll('select,input').forEach(el=>el.onchange=()=>dirty=true)});$$('.photo-button').forEach(b=>b.onclick=()=>openPhoto(b.dataset.img,b.dataset.title))}
function readExercise(card){return {level:card.querySelector('.ex-level').value,sets:card.querySelector('.ex-sets').value,reps:card.querySelector('.ex-reps').value,pain:card.querySelector('.ex-pain').value}}
function openPhoto(src,title){$('#photoModal img').src=src;$('#photoModalTitle').textContent=title;$('#photoModal').classList.remove('hidden')}
function loadSessionToUI(){const s=currentSession();$('#painBefore').value=s.painBefore??'';$('#painAfter').value=s.painAfter??'';$('#painLater').value=s.painLater??'';$('#painNextDay').value=s.painNextDay??'';$('#pain24h').checked=!!s.pain24h;$('#warmupMinutes').value=s.warmup?.minutes??10;$('#warmupEffort').value=s.warmup?.effort??'';$('#sessionNote').value=s.note||'';renderExercises();renderAlert()}
function collectSession(){const s=currentSession();s.painBefore=$('#painBefore').value;s.painAfter=$('#painAfter').value;s.painLater=$('#painLater').value;s.painNextDay=$('#painNextDay').value;s.pain24h=$('#pain24h').checked;s.warmup={minutes:$('#warmupMinutes').value,effort:$('#warmupEffort').value};s.note=$('#sessionNote').value;$$('.exercise-card').forEach(c=>s.exercises[c.dataset.ex]=readExercise(c));dirty=true;renderAlert()}
function renderAlert(){const s=currentSession(),vals=[s.painAfter,s.painLater,s.painNextDay,...Object.values(s.exercises||{}).map(v=>v.pain)].filter(v=>v!=='');const high=vals.some(v=>Number(v)>5);$('#guidanceAlert').classList.toggle('hidden',!(high||s.pain24h));$('#guidanceAlert').innerHTML=high||s.pain24h?`<strong>Bespreek aanpassing met je fysiotherapeut.</strong>${high?' Er is een pijnscore boven 5 geregistreerd.':''}${s.pain24h?' Verhoogde pijn houdt langer dan 24 uur aan.':''}`:''}
function updateSaveStatus(t){if($('#saveStatus'))$('#saveStatus').textContent=t}
function showMain(){unlocked=true;$('#lockScreen').classList.add('hidden');$('#setupScreen').classList.add('hidden');$('#mainApp').classList.remove('hidden');initMain()}
function initMain(){['painBefore','painAfter','painLater','painNextDay'].forEach(id=>$('#'+id).innerHTML=painOptions());renderLegend();$('#sessionDate').value=todayISO();$('#exportWeek').value=todayISO();$('#profileName').value=state.profile?.name||'';$('#profileDob').value=state.profile?.dob||'';loadSessionToUI();renderStats()}
function lock(){unlocked=false;$('#mainApp').classList.add('hidden');$('#lockScreen').classList.remove('hidden');$('#pinLogin').value=''}
$('#finishSetup').onclick=async()=>{const name=$('#setupName').value.trim(),dob=$('#setupDob').value,pin=$('#setupPin').value;if(!name||!dob||!validPin(pin))return $('#setupError').textContent='Vul naam, geboortedatum en een pincode van 4–8 cijfers in.';state.profile={name,dob};state.pinHash=await hash(pin);persist();showMain()};
$('#unlockBtn').onclick=async()=>{if(await hash($('#pinLogin').value)===state.pinHash){$('#pinError').textContent='';showMain()}else $('#pinError').textContent='Onjuiste pincode.'};$('#pinLogin').addEventListener('keydown',e=>{if(e.key==='Enter')$('#unlockBtn').click()});
$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===btn));$$('.tabpanel').forEach(p=>p.classList.toggle('active',p.id===btn.dataset.tab));if(btn.dataset.tab==='stats')renderStats();if(btn.dataset.tab==='export')renderExportPreview()});
$('#sessionDate').onchange=loadSessionToUI;['painBefore','painAfter','painLater','painNextDay','pain24h','warmupMinutes','warmupEffort','sessionNote'].forEach(id=>$('#'+id).addEventListener('input',()=>{dirty=true;collectSession()}));$('#saveSession').onclick=()=>{collectSession();persist();renderStats()};$('#manualSave').onclick=()=>{collectSession();persist()};setInterval(()=>{if(unlocked&&dirty){collectSession();persist()}},60000);window.addEventListener('beforeunload',()=>{if(unlocked&&dirty){collectSession();localStorage.setItem(KEY,JSON.stringify(state))}});
$('#saveProfile').onclick=()=>{state.profile={name:$('#profileName').value.trim(),dob:$('#profileDob').value};persist()};$('#changePin').onclick=async()=>{const p=$('#newPin').value;if(!validPin(p))return alert('Gebruik 4–8 cijfers.');state.pinHash=await hash(p);persist();$('#newPin').value='';alert('Pincode gewijzigd.')};$('#lockNow').onclick=()=>{collectSession();persist();lock()};
function sessionArray(days=9999){const cutoff=new Date();cutoff.setDate(cutoff.getDate()-days);return Object.values(state.sessions).filter(s=>new Date(s.date)>=cutoff).sort((a,b)=>a.date.localeCompare(b.date))} function avg(a){const v=a.map(Number).filter(Number.isFinite);return v.length?v.reduce((x,y)=>x+y,0)/v.length:null} function sessionAvgLevel(s){return avg(Object.values(s.exercises||{}).map(x=>x.level).filter(x=>x!==''))} function sessionAvgPain(s){const all=[s.painBefore,s.painAfter,...Object.values(s.exercises||{}).map(x=>x.pain)].filter(x=>x!==null&&x!=='');return avg(all)}
function renderStats(){if(!$('#statsRange'))return;const arr=sessionArray(Number($('#statsRange').value||28)),ap=avg(arr.map(sessionAvgPain).filter(x=>x!==null)),al=avg(arr.map(sessionAvgLevel).filter(x=>x!==null)),an=avg(arr.map(s=>s.painNextDay).filter(x=>x!==''&&x!=null));$('#mSessions').textContent=arr.length;$('#mAvgPain').textContent=ap==null?'–':ap.toFixed(1);$('#mAvgLevel').textContent=al==null?'–':al.toFixed(1);$('#mNextPain').textContent=an==null?'–':an.toFixed(1);drawScatter($('#levelPainChart'),arr);drawPainDates($('#painDateChart'),arr);renderExerciseScores(arr);renderWeekly(arr)} $('#statsRange').onchange=renderStats;
function clearCanvas(c){const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#d8dfda';for(let i=0;i<=5;i++){let y=30+i*(h-60)/5;ctx.beginPath();ctx.moveTo(45,y);ctx.lineTo(w-20,y);ctx.stroke()}return ctx} function drawScatter(c,arr){const ctx=clearCanvas(c),w=c.width,h=c.height;ctx.fillStyle='#69766f';ctx.font='18px sans-serif';ctx.fillText('Pijn 10',4,38);ctx.fillText('0',25,h-28);ctx.fillText('Niveau →',w-110,h-8);arr.forEach(s=>{let x=sessionAvgLevel(s),y=sessionAvgPain(s);if(x==null||y==null)return;ctx.beginPath();ctx.arc(45+(x/4)*(w-75),h-30-(y/10)*(h-60),7,0,Math.PI*2);ctx.fillStyle='#596f61';ctx.fill()})} function drawPainDates(c,arr){const ctx=clearCanvas(c),w=c.width,h=c.height;if(!arr.length)return;const vals=arr.map(sessionAvgPain);ctx.strokeStyle='#596f61';ctx.lineWidth=4;ctx.beginPath();vals.forEach((v,i)=>{if(v==null)return;const x=45+(i/Math.max(1,arr.length-1))*(w-75),y=h-30-(v/10)*(h-60);i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);ctx.fillStyle='#596f61';ctx.fillRect(x-4,y-4,8,8)});ctx.stroke()}
function renderExerciseScores(arr){$('#exerciseScores').innerHTML=exercises.map(ex=>{const score=avg(arr.map(s=>s.exercises?.[ex.id]?.level).filter(x=>x));return `<div class="score-row"><div><strong>${ex.id} ${ex.name}</strong><div class="bar"><span style="width:${score?score/4*100:0}%"></span></div></div><div>${score?score.toFixed(1):'–'} / 4</div></div>`}).join('')} function weekKey(d){const x=new Date(d+'T12:00:00'),f=new Date(x);f.setDate(x.getDate()-((x.getDay()+6)%7));return f.toISOString().slice(0,10)} function renderWeekly(arr){const g={};arr.forEach(s=>(g[weekKey(s.date)]??=[]).push(s));$('#weeklyProgress').innerHTML=Object.entries(g).sort().map(([w,ss])=>`<div class="week-row"><div><strong>Week vanaf ${w}</strong><br><small>${ss.length} training(en)</small></div><div>Niveau ${avg(ss.map(sessionAvgLevel).filter(x=>x!=null))?.toFixed(1)??'–'} • Pijn ${avg(ss.map(sessionAvgPain).filter(x=>x!=null))?.toFixed(1)??'–'}</div></div>`).join('')||'<p>Nog geen gegevens.</p>'}
function weekSessions(ds){const d=new Date(ds+'T12:00:00'),start=new Date(d);start.setDate(d.getDate()-((d.getDay()+6)%7));const end=new Date(start);end.setDate(start.getDate()+6);return Object.values(state.sessions).filter(s=>{const x=new Date(s.date+'T12:00:00');return x>=start&&x<=end}).sort((a,b)=>a.date.localeCompare(b.date))}
function csvForWeek(){const rows=[['Datum','Oefening','Niveau','Sets','Herhalingen/set','Pijn oefening','Pijn voor','Pijn na','Pijn later','Pijn volgende dag','Pijn >24u','Opmerking']];weekSessions($('#exportWeek').value||todayISO()).forEach(s=>{const es=Object.entries(s.exercises||{}).filter(([,v])=>v.level||v.pain||v.reps||v.sets);if(!es.length)es.push(['',{}]);es.forEach(([id,v])=>rows.push([s.date,id?`${id} ${exercises.find(e=>e.id===id)?.name||id}`:'',v.level||'',v.sets||'',v.reps||'',v.pain||'',s.painBefore||'',s.painAfter||'',s.painLater||'',s.painNextDay||'',s.pain24h?'Ja':'Nee',s.note||'']))});return rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(';')).join('\n')}
function renderExportPreview(){const t=csvForWeek();$('#exportPreview').textContent=t.split('\n').slice(0,12).join('\n')+(t.split('\n').length>12?'\n…':'')} $('#previewExport').onclick=renderExportPreview;$('#exportWeek').onchange=renderExportPreview;function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)} $('#downloadExport').onclick=()=>downloadBlob(new Blob(['\ufeff'+csvForWeek()],{type:'text/csv;charset=utf-8'}),'GLAD-weekrapport-'+($('#exportWeek').value||todayISO())+'.csv');$('#shareExport').onclick=async()=>{const file=new File(['\ufeff'+csvForWeek()],'GLAD-weekrapport.csv',{type:'text/csv'});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:'GLA:D weekrapport',files:[file]});else downloadBlob(file,'GLAD-weekrapport.csv')};$('#backupBtn').onclick=()=>downloadBlob(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'GLAD-backup-'+todayISO()+'.json');$('#restoreFile').onchange=async e=>{try{const o=JSON.parse(await e.target.files[0].text());if(!o.profile||!o.sessions)throw 0;state={...defaultState(),...o};persist();initMain();alert('Back-up hersteld.')}catch{alert('Geen geldige GLA:D-back-up.')}};
$('#closePhoto').onclick=()=>$('#photoModal').classList.add('hidden');$('#photoModal').onclick=e=>{if(e.target.id==='photoModal')$('#photoModal').classList.add('hidden')};
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(!state.profile||!state.pinHash)$('#setupScreen').classList.remove('hidden');else $('#lockScreen').classList.remove('hidden');
